[profile.default]
via-ir = true
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@hyperlane/=hyperlane-monorepo/solidity/"
]
optimizer = true
optimizer_runs = 200
